name: sewa-sanjal

services:
  backend:
    container_name: sewa-sanjal-dev

    build:
      context: .
      dockerfile: ./Dockerfile

    image: sewa-sanjal:dev

    env_file:
      - .env

    ports:
      - "4000:4000"
      - "3000:3000"

    environment:
      NODE_ENV: development

    volumes:
      - ./backend/public:/app/backend/public

    networks:
      - mariadb-net

    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
            - dist/
            - backend/public/

        - action: rebuild
          path: ./package.json

        - action: rebuild
          path: ./bun.lock

        - action: rebuild
          path: ./Dockerfile

        - action: rebuild
          path: ./.env

        - action: rebuild
          path: ./docker-compose.yml

networks:
  mariadb-net:
    external: true
